package com.example.Queries.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.example.Queries.entity.Tbprb;
import com.example.Queries.entity.TbprbNew;
import com.example.Queries.entity.Tbprbbyhour;
import com.example.Queries.mapper.TbprbMapper;
import com.example.Queries.service.TbprbService;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * <p>
 *  服务实现类
 * </p>
 *
 * @author nanaiii
 * @since 2021-04-26
 */
@Service
public class TbprbServiceImpl extends ServiceImpl<TbprbMapper, Tbprb> implements TbprbService {

    @Override
    public List<Tbprbbyhour> getHourList(List<Tbprb> quarter) {
        List<Tbprbbyhour> tmpList = new ArrayList<>();
        double[] t = new double[100];
        double num = 4;
        for (Tbprb i : quarter){
//            String date = i.getStartTime().split(" ")[0];
//            String minute = i.getStartTime().split(" ")[1].split(":")[1];
//            String hour = i.getStartTime().split(" ")[1].split(":")[0];
            //  对每个t计算
            if(1==1){
                t[0] += i.getT0();
                t[1] += i.getT1();
                t[2] += i.getT2();
                t[3] += i.getT3();
                t[4] += i.getT4();
                t[5] += i.getT5();
                t[6] += i.getT6();
                t[7] += i.getT7();
                t[8] += i.getT8();
                t[9] += i.getT9();
                t[10] += i.getT10();
                t[11] += i.getT11();
                t[12] += i.getT12();
                t[13] += i.getT13();
                t[14] += i.getT14();
                t[15] += i.getT15();
                t[16] += i.getT16();
                t[17] += i.getT17();
                t[18] += i.getT18();
                t[19] += i.getT19();
                t[20] += i.getT20();
                t[21] += i.getT21();
                t[22] += i.getT22();
                t[23] += i.getT23();
                t[24] += i.getT24();
                t[25] += i.getT25();
                t[26] += i.getT26();
                t[27] += i.getT27();
                t[28] += i.getT28();
                t[29] += i.getT29();
                t[30] += i.getT30();
                t[31] += i.getT31();
                t[32] += i.getT32();
                t[33] += i.getT33();
                t[34] += i.getT34();
                t[35] += i.getT35();
                t[36] += i.getT36();
                t[37] += i.getT37();
                t[38] += i.getT38();
                t[39] += i.getT39();
                t[40] += i.getT40();
                t[41] += i.getT41();
                t[42] += i.getT42();
                t[43] += i.getT43();
                t[44] += i.getT44();
                t[45] += i.getT45();
                t[46] += i.getT46();
                t[47] += i.getT47();
                t[48] += i.getT48();
                t[49] += i.getT49();
                t[50] += i.getT50();
                t[51] += i.getT51();
                t[52] += i.getT52();
                t[53] += i.getT53();
                t[54] += i.getT54();
                t[55] += i.getT55();
                t[56] += i.getT56();
                t[57] += i.getT57();
                t[58] += i.getT58();
                t[59] += i.getT59();
                t[60] += i.getT60();
                t[61] += i.getT61();
                t[62] += i.getT62();
                t[63] += i.getT63();
                t[64] += i.getT64();
                t[65] += i.getT65();
                t[66] += i.getT66();
                t[67] += i.getT67();
                t[68] += i.getT68();
                t[69] += i.getT69();
                t[70] += i.getT70();
                t[71] += i.getT71();
                t[72] += i.getT72();
                t[73] += i.getT73();
                t[74] += i.getT74();
                t[75] += i.getT75();
                t[76] += i.getT76();
                t[77] += i.getT77();
                t[78] += i.getT78();
                t[79] += i.getT79();
                t[80] += i.getT80();
                t[81] += i.getT81();
                t[82] += i.getT82();
                t[83] += i.getT83();
                t[84] += i.getT84();
                t[85] += i.getT85();
                t[86] += i.getT86();
                t[87] += i.getT87();
                t[88] += i.getT88();
                t[89] += i.getT89();
                t[90] += i.getT90();
                t[91] += i.getT91();
                t[92] += i.getT92();
                t[93] += i.getT93();
                t[94] += i.getT94();
                t[95] += i.getT95();
                t[96] += i.getT96();
                t[97] += i.getT97();
                t[98] += i.getT98();
                t[99] += i.getT99();
            }

            if(i.getStartTime().split(" ")[1].split(":")[1].equals("45")){//add to list
                Tbprbbyhour tbprb = new Tbprbbyhour();
                tbprb.setENode(i.getCellName().substring(0,i.getCellName().length()-2));
                tbprb.setStartTime(i.getStartTime().split(" ")[0]+":"+i.getStartTime().split(" ")[1].split(":")[0]);
                tbprb.setCellDesc(i.getCellDesc());
                tbprb.setCellName(i.getCellName());
                if(1==1){
                    tbprb.setT0(t[0]/num);
                    tbprb.setT1(t[1]/num);
                    tbprb.setT2(t[2]/num);
                    tbprb.setT3(t[3]/num);
                    tbprb.setT4(t[4]/num);
                    tbprb.setT5(t[5]/num);
                    tbprb.setT6(t[6]/num);
                    tbprb.setT7(t[7]/num);
                    tbprb.setT8(t[8]/num);
                    tbprb.setT9(t[9]/num);
                    tbprb.setT10(t[10]/num);
                    tbprb.setT11(t[11]/num);
                    tbprb.setT12(t[12]/num);
                    tbprb.setT13(t[13]/num);
                    tbprb.setT14(t[14]/num);
                    tbprb.setT15(t[15]/num);
                    tbprb.setT16(t[16]/num);
                    tbprb.setT17(t[17]/num);
                    tbprb.setT18(t[18]/num);
                    tbprb.setT19(t[19]/num);
                    tbprb.setT20(t[20]/num);
                    tbprb.setT21(t[21]/num);
                    tbprb.setT22(t[22]/num);
                    tbprb.setT23(t[23]/num);
                    tbprb.setT24(t[24]/num);
                    tbprb.setT25(t[25]/num);
                    tbprb.setT26(t[26]/num);
                    tbprb.setT27(t[27]/num);
                    tbprb.setT28(t[28]/num);
                    tbprb.setT29(t[29]/num);
                    tbprb.setT30(t[30]/num);
                    tbprb.setT31(t[31]/num);
                    tbprb.setT32(t[32]/num);
                    tbprb.setT33(t[33]/num);
                    tbprb.setT34(t[34]/num);
                    tbprb.setT35(t[35]/num);
                    tbprb.setT36(t[36]/num);
                    tbprb.setT37(t[37]/num);
                    tbprb.setT38(t[38]/num);
                    tbprb.setT39(t[39]/num);
                    tbprb.setT40(t[40]/num);
                    tbprb.setT41(t[41]/num);
                    tbprb.setT42(t[42]/num);
                    tbprb.setT43(t[43]/num);
                    tbprb.setT44(t[44]/num);
                    tbprb.setT45(t[45]/num);
                    tbprb.setT46(t[46]/num);
                    tbprb.setT47(t[47]/num);
                    tbprb.setT48(t[48]/num);
                    tbprb.setT49(t[49]/num);
                    tbprb.setT50(t[50]/num);
                    tbprb.setT51(t[51]/num);
                    tbprb.setT52(t[52]/num);
                    tbprb.setT53(t[53]/num);
                    tbprb.setT54(t[54]/num);
                    tbprb.setT55(t[55]/num);
                    tbprb.setT56(t[56]/num);
                    tbprb.setT57(t[57]/num);
                    tbprb.setT58(t[58]/num);
                    tbprb.setT59(t[59]/num);
                    tbprb.setT60(t[60]/num);
                    tbprb.setT61(t[61]/num);
                    tbprb.setT62(t[62]/num);
                    tbprb.setT63(t[63]/num);
                    tbprb.setT64(t[64]/num);
                    tbprb.setT65(t[65]/num);
                    tbprb.setT66(t[66]/num);
                    tbprb.setT67(t[67]/num);
                    tbprb.setT68(t[68]/num);
                    tbprb.setT69(t[69]/num);
                    tbprb.setT70(t[70]/num);
                    tbprb.setT71(t[71]/num);
                    tbprb.setT72(t[72]/num);
                    tbprb.setT73(t[73]/num);
                    tbprb.setT74(t[74]/num);
                    tbprb.setT75(t[75]/num);
                    tbprb.setT76(t[76]/num);
                    tbprb.setT77(t[77]/num);
                    tbprb.setT78(t[78]/num);
                    tbprb.setT79(t[79]/num);
                    tbprb.setT80(t[80]/num);
                    tbprb.setT81(t[81]/num);
                    tbprb.setT82(t[82]/num);
                    tbprb.setT83(t[83]/num);
                    tbprb.setT84(t[84]/num);
                    tbprb.setT85(t[85]/num);
                    tbprb.setT86(t[86]/num);
                    tbprb.setT87(t[87]/num);
                    tbprb.setT88(t[88]/num);
                    tbprb.setT89(t[89]/num);
                    tbprb.setT90(t[90]/num);
                    tbprb.setT91(t[91]/num);
                    tbprb.setT92(t[92]/num);
                    tbprb.setT93(t[93]/num);
                    tbprb.setT94(t[94]/num);
                    tbprb.setT95(t[95]/num);
                    tbprb.setT96(t[96]/num);
                    tbprb.setT97(t[97]/num);
                    tbprb.setT98(t[98]/num);
                    tbprb.setT99(t[99]/num);
                }
                tmpList.add(tbprb);
                for(int j=0;j<100;j++){
                    t[j]=0.0;
                }
//                System.out.println("ADD to List data:"+tbprb.getStartTime()+" "+tbprb.getENode()+"\n\n");
            }
//            if(minute.equals("45")){//add to list
//                Execlprb execlprb = new Execlprb();
//                execlprb.setCellDesc(i.getCellDesc());
//                execlprb.setCellName(i.getCellName());
//                execlprb.setENode(i.getENode());
//                execlprb.setStartTime(date+":"+hour);
//                execlprb.setTot(tByHour/4);
//                tByHour = 0.0;
//                tmpList.add(execlprb);
//            }
        }
//        System.out.println("In TbprbServiceImpl"+tmpList.size());
        return tmpList;
    }

    @Override
    public List<TbprbNew> getHourByOneList(int num, String ENode, int t, String start, String end) {
        List<TbprbNew> tmpList = new ArrayList<>();
        int sum = 0;
        int count = 1;

        String selectSql = "start_time as time,t"+String.valueOf(t)+" as t";
        QueryWrapper<Tbprb> wrapper = new QueryWrapper<>();
        wrapper.between("start_time", start, end);
        wrapper.eq("eNode", ENode);
        wrapper.select(selectSql);
        List<Map<String ,Object>>  quarter = baseMapper.selectMaps(wrapper);
        for (Map<String ,Object> i : quarter){
            String time = (String) i.get("time");
//            String day = time.split(" ")[0];
//            String minute = i.getStartTime().split(" ")[1].split(":")[1];
//            String hour = time.split(" ")[1].split(":")[0];
            sum += (int) i.get("t");
            count++;
            if(count%num==0) {//add to list
                TbprbNew tbprbNew = new TbprbNew();
                tbprbNew.setENode(ENode);
//                System.out.println(tbprbNew.getENode()+"\n");
                tbprbNew.setStartTime(time.split(" ")[0] + ":" + time.split(" ")[1].split(":")[0]);
                tbprbNew.setT((double)sum / (double) num);
                tmpList.add(tbprbNew);
                sum = 0;
            }
        }
        return tmpList;
    }
}


//            //  对每个t计算
//            t[0] += i.getT0();
//            t[1] += i.getT1();
//            t[2] += i.getT2();
//            t[3] += i.getT3();
//            t[4] += i.getT4();
//            t[5] += i.getT5();
//            t[6] += i.getT6();
//            t[7] += i.getT7();
//            t[8] += i.getT8();
//            t[9] += i.getT9();
//            t[10] += i.getT10();
//            t[11] += i.getT11();
//            t[12] += i.getT12();
//            t[13] += i.getT13();
//            t[14] += i.getT14();
//            t[15] += i.getT15();
//            t[16] += i.getT16();
//            t[17] += i.getT17();
//            t[18] += i.getT18();
//            t[19] += i.getT19();
//            t[20] += i.getT20();
//            t[21] += i.getT21();
//            t[22] += i.getT22();
//            t[23] += i.getT23();
//            t[24] += i.getT24();
//            t[25] += i.getT25();
//            t[26] += i.getT26();
//            t[27] += i.getT27();
//            t[28] += i.getT28();
//            t[29] += i.getT29();
//            t[30] += i.getT30();
//            t[31] += i.getT31();
//            t[32] += i.getT32();
//            t[33] += i.getT33();
//            t[34] += i.getT34();
//            t[35] += i.getT35();
//            t[36] += i.getT36();
//            t[37] += i.getT37();
//            t[38] += i.getT38();
//            t[39] += i.getT39();
//            t[40] += i.getT40();
//            t[41] += i.getT41();
//            t[42] += i.getT42();
//            t[43] += i.getT43();
//            t[44] += i.getT44();
//            t[45] += i.getT45();
//            t[46] += i.getT46();
//            t[47] += i.getT47();
//            t[48] += i.getT48();
//            t[49] += i.getT49();
//            t[50] += i.getT50();
//            t[51] += i.getT51();
//            t[52] += i.getT52();
//            t[53] += i.getT53();
//            t[54] += i.getT54();
//            t[55] += i.getT55();
//            t[56] += i.getT56();
//            t[57] += i.getT57();
//            t[58] += i.getT58();
//            t[59] += i.getT59();
//            t[60] += i.getT60();
//            t[61] += i.getT61();
//            t[62] += i.getT62();
//            t[63] += i.getT63();
//            t[64] += i.getT64();
//            t[65] += i.getT65();
//            t[66] += i.getT66();
//            t[67] += i.getT67();
//            t[68] += i.getT68();
//            t[69] += i.getT69();
//            t[70] += i.getT70();
//            t[71] += i.getT71();
//            t[72] += i.getT72();
//            t[73] += i.getT73();
//            t[74] += i.getT74();
//            t[75] += i.getT75();
//            t[76] += i.getT76();
//            t[77] += i.getT77();
//            t[78] += i.getT78();
//            t[79] += i.getT79();
//            t[80] += i.getT80();
//            t[81] += i.getT81();
//            t[82] += i.getT82();
//            t[83] += i.getT83();
//            t[84] += i.getT84();
//            t[85] += i.getT85();
//            t[86] += i.getT86();
//            t[87] += i.getT87();
//            t[88] += i.getT88();
//            t[89] += i.getT89();
//            t[90] += i.getT90();
//            t[91] += i.getT91();
//            t[92] += i.getT92();
//            t[93] += i.getT93();
//            t[94] += i.getT94();
//            t[95] += i.getT95();
//            t[96] += i.getT96();
//            t[97] += i.getT97();
//            t[98] += i.getT98();
//            t[99] += i.getT99();
//            if(count%num==0){//add to list
//                Tbprb tbprb = new Tbprb();
//                tbprb.setENode(i.getCellName().substring(0,i.getCellName().length()-2));
//                tbprb.setStartTime(date+":"+hour);
//                tbprb.setT0(t[0]/num);
//                tbprb.setT1(t[1]/num);
//                tbprb.setT2(t[2]/num);
//                tbprb.setT3(t[3]/num);
//                tbprb.setT4(t[4]/num);
//                tbprb.setT5(t[5]/num);
//                tbprb.setT6(t[6]/num);
//                tbprb.setT7(t[7]/num);
//                tbprb.setT8(t[8]/num);
//                tbprb.setT9(t[9]/num);
//                tbprb.setT10(t[10]/num);
//                tbprb.setT11(t[11]/num);
//                tbprb.setT12(t[12]/num);
//                tbprb.setT13(t[13]/num);
//                tbprb.setT14(t[14]/num);
//                tbprb.setT15(t[15]/num);
//                tbprb.setT16(t[16]/num);
//                tbprb.setT17(t[17]/num);
//                tbprb.setT18(t[18]/num);
//                tbprb.setT19(t[19]/num);
//                tbprb.setT20(t[20]/num);
//                tbprb.setT21(t[21]/num);
//                tbprb.setT22(t[22]/num);
//                tbprb.setT23(t[23]/num);
//                tbprb.setT24(t[24]/num);
//                tbprb.setT25(t[25]/num);
//                tbprb.setT26(t[26]/num);
//                tbprb.setT27(t[27]/num);
//                tbprb.setT28(t[28]/num);
//                tbprb.setT29(t[29]/num);
//                tbprb.setT30(t[30]/num);
//                tbprb.setT31(t[31]/num);
//                tbprb.setT32(t[32]/num);
//                tbprb.setT33(t[33]/num);
//                tbprb.setT34(t[34]/num);
//                tbprb.setT35(t[35]/num);
//                tbprb.setT36(t[36]/num);
//                tbprb.setT37(t[37]/num);
//                tbprb.setT38(t[38]/num);
//                tbprb.setT39(t[39]/num);
//                tbprb.setT40(t[40]/num);
//                tbprb.setT41(t[41]/num);
//                tbprb.setT42(t[42]/num);
//                tbprb.setT43(t[43]/num);
//                tbprb.setT44(t[44]/num);
//                tbprb.setT45(t[45]/num);
//                tbprb.setT46(t[46]/num);
//                tbprb.setT47(t[47]/num);
//                tbprb.setT48(t[48]/num);
//                tbprb.setT49(t[49]/num);
//                tbprb.setT50(t[50]/num);
//                tbprb.setT51(t[51]/num);
//                tbprb.setT52(t[52]/num);
//                tbprb.setT53(t[53]/num);
//                tbprb.setT54(t[54]/num);
//                tbprb.setT55(t[55]/num);
//                tbprb.setT56(t[56]/num);
//                tbprb.setT57(t[57]/num);
//                tbprb.setT58(t[58]/num);
//                tbprb.setT59(t[59]/num);
//                tbprb.setT60(t[60]/num);
//                tbprb.setT61(t[61]/num);
//                tbprb.setT62(t[62]/num);
//                tbprb.setT63(t[63]/num);
//                tbprb.setT64(t[64]/num);
//                tbprb.setT65(t[65]/num);
//                tbprb.setT66(t[66]/num);
//                tbprb.setT67(t[67]/num);
//                tbprb.setT68(t[68]/num);
//                tbprb.setT69(t[69]/num);
//                tbprb.setT70(t[70]/num);
//                tbprb.setT71(t[71]/num);
//                tbprb.setT72(t[72]/num);
//                tbprb.setT73(t[73]/num);
//                tbprb.setT74(t[74]/num);
//                tbprb.setT75(t[75]/num);
//                tbprb.setT76(t[76]/num);
//                tbprb.setT77(t[77]/num);
//                tbprb.setT78(t[78]/num);
//                tbprb.setT79(t[79]/num);
//                tbprb.setT80(t[80]/num);
//                tbprb.setT81(t[81]/num);
//                tbprb.setT82(t[82]/num);
//                tbprb.setT83(t[83]/num);
//                tbprb.setT84(t[84]/num);
//                tbprb.setT85(t[85]/num);
//                tbprb.setT86(t[86]/num);
//                tbprb.setT87(t[87]/num);
//                tbprb.setT88(t[88]/num);
//                tbprb.setT89(t[89]/num);
//                tbprb.setT90(t[90]/num);
//                tbprb.setT91(t[91]/num);
//                tbprb.setT92(t[92]/num);
//                tbprb.setT93(t[93]/num);
//                tbprb.setT94(t[94]/num);
//                tbprb.setT95(t[95]/num);
//                tbprb.setT96(t[96]/num);
//                tbprb.setT97(t[97]/num);
//                tbprb.setT98(t[98]/num);
//                tbprb.setT99(t[99]/num);
//                tmpList.add(tbprb);
//                for(int j=0;j<100;j++){
//                    t[j]=0;
//                }
//                System.out.println("ADD to List data:"+tbprb.getStartTime()+"   sum:"+tbprb.getT0()+"\n\n");
//            }
